### PR TITLE
Copy bluetail/silvereye apps from the bluetail repo

### PR DESCRIPTION
**Pull request by SimKennedy**
This PR copies in the bluetail and silvereye app directories from the `bluetail` repository (https://github.com/mysociety/bluetail) and makes the required changes to work in `cove-ocds`.

Detailed changes added to README.md and below.
- This PR copies the bluetail/silvereye directories in entirety for simplicity. 
- Note this PR copies the `bluetail/vendor/bootstrap` directory from `bluetail` but does NOT keep it as a submodule. Since the submodule is now pinned to v4.5.0 and not likely to change this should not be a problem, but there is likely a lot of files that are not needed.
  - Initial tests suggest we could remove all other subdirectories and just keep these for the styling
    ```
    bluetail/vendor/bootstrap/dist
    bluetail/vendor/bootstrap/js
    bluetail/vendor/bootstrap/scss
    ```

## Steps taken when merging Bluetail/Silvereye into cove-ocds

- copy bluetail/silvereye app directories
- update INSTALLED_APPS:

        'bluetail',
        'silvereye',
        'django_pgviews',
        'pipeline',
    
- updated settings.py 
    - Need BLUETAIL_APP_DIR for management commands
    
        ```
        BLUETAIL_APP_DIR = os.path.join(BASE_DIR, "bluetail")
        ```
      
    - Add bluetail/silvereye template dirs
    
        ```
        TEMPLATES[0]["DIRS"] = [os.path.join(BASE_DIR, "bluetail", "templates")]
        TEMPLATES[0]["DIRS"] = [os.path.join(BASE_DIR, "silvereye", "templates")]
        ```
      
    - Django pipeline and static settings
    
        ```
        if DEBUG:
            IS_LIVE = False
            STATICFILES_STORAGE = 'pipeline.storage.NonPackagingPipelineStorage'
        else:
            IS_LIVE = True
            STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'

        STATICFILES_FINDERS = (
            'django.contrib.staticfiles.finders.FileSystemFinder',
            'django.contrib.staticfiles.finders.AppDirectoriesFinder',
            'pipeline.finders.PipelineFinder',
        )

        VENDOR_DIR = os.path.join(BLUETAIL_APP_DIR, "vendor")
        # Define some custom locations at which the staticfiles app can find our
        # files, which it will collect in the directory defined by `STATIC_ROOT`.
        # django-pipeline will then compile them from there (if required).
        STATICFILES_DIRS = (
            (
                "bootstrap",
                os.path.join(VENDOR_DIR, "bootstrap", "scss"),
            ),
            (
                "html5shiv",
                os.path.join(VENDOR_DIR, "html5shiv"),
            ),
            (
                "jquery",
                os.path.join(VENDOR_DIR, "jquery"),
            ),
            (
                "bootstrap",
                os.path.join(VENDOR_DIR, "bootstrap", "dist", "js"),
            )
        )

        SASS_BINARY = os.getenv('SASS_BINARY', 'sassc')

        PIPELINE = {
            'STYLESHEETS': {
                'main': {
                    'source_filenames': (
                        'sass/main.scss',
                    ),
                    'output_filename': 'css/main.css',
                },
            },

            'CSS_COMPRESSOR': 'django_pipeline_csscompressor.CssCompressor',
            'DISABLE_WRAPPER': True,
            'COMPILERS': (
                'pipeline.compilers.sass.SASSCompiler',
            ),
            'SHOW_ERRORS_INLINE': False,
            # Use the libsass commandline tool (that's bundled with libsass) as our
            # sass compiler, so there's no need to install anything else.
            'SASS_BINARY': SASS_BINARY,
        }
        ```
- Add url paths to project urls.py
    
    ```
    path(r'', include('bluetail.urls')),
    path('publisher-hub/', include('silvereye.urls')),
    ```
 
- Run commands for migrations and data 

    ```   
    python manage.py migrate
    python manage.py sync_pgviews --force
    python manage.py insert_prototype_data


    python manage.py insert_contracts_finder_data --anonymise
    python manage.py generate_fake_popolo > fake_popolo.json
    python manage.py load_identifiers_from_popolo fake_popolo.json person_id_matches_cabinet_minister
    rm fake_popolo.json
    python manage.py scan_contracts
    ```

- Update .gitignore with the /static/ dir

    ```
    /static/
    ```

### CODE REVIEW

**Comment by SimKennedy** [comment]
> This seems to be working for me, yay!
> 
> One thought: the `path(r'', include('bluetail.urls'))` bit can probably be removed from `urls.py`. It's not reachable because there's already a redirect on the root path, and I don't think we'll be using any bluetail URLs here anyway.

Thanks @chrismytton 

I added this line to include all of the URLs from bluetail/urls.py at the root path to test things were working, but below the other root endpoint so it would not interfere with the `cove-ocds` behaviour.

`url(r"^$", RedirectView.as_view(url="review/", permanent=False)),`

So even though the bluetail root is not reachable, this still enables the other URLs from bluetail so we can reach the `/tenders/*` endpoints if we wanted.

You're right don't necessarily need bluetail working, but thought it would be useful if we need to test changes to the shared CSS/static files during development? Eg. the bootstrap optimising I mentioned in the description (which I'd appreciate your thoughts?)

**Comment by chrismytton** [comment]
@SimKennedy that all makes sense.

Regarding Bootstrap, it makes sense to just copy over the bits that we need, rather than add the whole repo. That might be a bit tricky though, since we'll probably need all of the source SCSS files, any images they reference, and possibly any javascript that's needed.

If it's easy to strip back Bootstrap to just the bits we're using then let's do it. Otherwise I think it's fine to leave the extra bits in for now.

**Comment by SimKennedy** [comment]
> @SimKennedy that all makes sense.
> 
> Regarding Bootstrap, it makes sense to just copy over the bits that we need, rather than add the whole repo. That might be a bit tricky though, since we'll probably need all of the source SCSS files, any images they reference, and possibly any javascript that's needed.
> 
> If it's easy to strip back Bootstrap to just the bits we're using then let's do it. Otherwise I think it's fine to leave the extra bits in for now.

Cool. I'm not totally confident of what bits Bootstrap needs or we use, but going by this on https://getbootstrap.com/docs/4.5/getting-started/contents/#bootstrap-source-code, 
```
bootstrap/
├── dist/
│   ├── css/
│   └── js/
├── site/
│   └──docs/
│      └── 4.5/
│          └── examples/
├── js/
└── scss/
```
I think we could at least remove all the extra git and build files or even switch to this download? 
For consistency would it make sense to do this in bluetail too? @zarino thoughts?

**Comment by chrismytton** [comment]
The Bootstrap tidying was done in https://github.com/mysociety/bluetail/pull/50. Thanks @SimKennedy!

I've copied those changes into this PR, along with the latest version of the bluetail and silvereye directory.

So I think this is ready to go. Going to merge this and start on a fresh branch, rather than have long-running branches.

**Comment by chrismytton** [comment]
All merged. Any new changes can be made in a branch from `master`.

**Pull request merged**
